spring:
  # parametrii de business stau separat, in config.yaml (langa application.yml)
  config.import: config.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: user
    password: pass
