package victor.training.spring.transaction.playground;

import jdk.jfr.DataAmount;
import lombok.Data;
import lombok.ToString;
import org.springframework.lang.Nullable;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.ArrayList;
import java.util.List;

@Entity
@Data // tostring is generated by lombok to include all fields, the problem is the 'tags' field (a colelction) by default layze loaded
@Table(uniqueConstraints = @UniqueConstraint(name = "UQ_MESSAGE",
    columnNames = "message"))
public class Message {
    @Id
    @GeneratedValue
    private Long id;
    @NotNull
    private String message;
    @ElementCollection
    @ToString.Exclude
    private List<String> tags = new ArrayList<>();

    protected Message() { // for hibernate only
    }

    public Message(String message) {
        this.message = message;
    }
}
