/*
 * This file is generated by jOOQ.
 */
package victor.training.spring.jooq.table;


import victor.training.spring.jooq.table.tables.Author;
import victor.training.spring.jooq.table.tables.AuthorBook;
import victor.training.spring.jooq.table.tables.Book;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>PUBLIC.AUTHOR_BOOK</code>.
     */
    public static final AuthorBook AUTHOR_BOOK = AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>PUBLIC.BOOK</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
